// Generated by gencpp from file f1tenth_simulator/gpiowrite.msg
// DO NOT EDIT!


#ifndef F1TENTH_SIMULATOR_MESSAGE_GPIOWRITE_H
#define F1TENTH_SIMULATOR_MESSAGE_GPIOWRITE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace f1tenth_simulator
{
template <class ContainerAllocator>
struct gpiowrite_
{
  typedef gpiowrite_<ContainerAllocator> Type;

  gpiowrite_()
    : state(false)
    , duration(0)  {
    }
  gpiowrite_(const ContainerAllocator& _alloc)
    : state(false)
    , duration(0)  {
  (void)_alloc;
    }



   typedef uint8_t _state_type;
  _state_type state;

   typedef uint8_t _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::f1tenth_simulator::gpiowrite_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::f1tenth_simulator::gpiowrite_<ContainerAllocator> const> ConstPtr;

}; // struct gpiowrite_

typedef ::f1tenth_simulator::gpiowrite_<std::allocator<void> > gpiowrite;

typedef boost::shared_ptr< ::f1tenth_simulator::gpiowrite > gpiowritePtr;
typedef boost::shared_ptr< ::f1tenth_simulator::gpiowrite const> gpiowriteConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::f1tenth_simulator::gpiowrite_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::f1tenth_simulator::gpiowrite_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::f1tenth_simulator::gpiowrite_<ContainerAllocator1> & lhs, const ::f1tenth_simulator::gpiowrite_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::f1tenth_simulator::gpiowrite_<ContainerAllocator1> & lhs, const ::f1tenth_simulator::gpiowrite_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace f1tenth_simulator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::f1tenth_simulator::gpiowrite_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::f1tenth_simulator::gpiowrite_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::f1tenth_simulator::gpiowrite_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::f1tenth_simulator::gpiowrite_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::f1tenth_simulator::gpiowrite_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::f1tenth_simulator::gpiowrite_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::f1tenth_simulator::gpiowrite_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e48107ec9af92b61adf575e5d66914d0";
  }

  static const char* value(const ::f1tenth_simulator::gpiowrite_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe48107ec9af92b61ULL;
  static const uint64_t static_value2 = 0xadf575e5d66914d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::f1tenth_simulator::gpiowrite_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1tenth_simulator/gpiowrite";
  }

  static const char* value(const ::f1tenth_simulator::gpiowrite_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::f1tenth_simulator::gpiowrite_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# set the pin to high or low via true/false\n"
"bool state\n"
"\n"
"# Optionally, provide duration for state. <= 0 will leave in state indefinitely.\n"
"uint8 duration\n"
;
  }

  static const char* value(const ::f1tenth_simulator::gpiowrite_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::f1tenth_simulator::gpiowrite_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gpiowrite_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::f1tenth_simulator::gpiowrite_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::f1tenth_simulator::gpiowrite_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
    s << indent << "duration: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // F1TENTH_SIMULATOR_MESSAGE_GPIOWRITE_H
